<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <title>Async and Await</title>
    <style>

    </style>
</head>
<body>
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>

    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.7.1.min.js" type="text/javascript"></script>

    <script type="text/javascript">

        function myfunone(){
            return "Hello Sir, I am myfunone";
        }

        console.log(myfunone());

        //async

        async function myfuntwo(){
            return "Hello Sir, i am funtwo";
        }
        console.log(myfuntwo()); //give promise result due to async

        console.log("Good Bye Sir");

        //to get real result of myfuntwo()
        myfuntwo().then((response)=>console.log(response));




        //async await
        async function myfunthree(){
            const setpromise = new Promise((resolve,reject)=>{
                setTimeout(()=>resolve("Hello World"),5000);
            }); 

            const response = await setpromise;
            return response;
        }

        console.log(myfunthree());
        console.log("Good Night Sir");

        //to get real result of myfunthree()
        myfunthree().then((response)=>console.log(response));


    //----------------------------------------------------------------------
        async function myfunfour(){
            const setpromise = new Promise((resolve,reject)=>{
                setTimeout(()=>resolve("Hello Moon"),3000);
            });

            // const error = true; 
            const error = false;  


            //This is condition is used to check internet connection in real world examples
            //this decide to give response or error
            if(!error){
                const response = await setpromise;
                return response;
            }else{
                await Promise.reject(new Error("Something went wrong !!!"));
            }
        }

        myfunfour()
            .then((response)=>console.log(response))  //response 
            .catch((err)=>console.log(err)); //reject 

        
        //----------------------------------------------------------------------
        

    </script>
    
</body>
</html>
